### ISSUE TITLE
C implementation uses a lot of memory (for use on a microcontroller)

### ISSUE THREAD

**Issue by redfast00** [line/aes-gcm-siv#1]
The C implementation has 5 look-up tables, which combined use 4352 bytes of memory:

```
// Forward S-box & tables
static uint8_t FSb[256];
static uint32_t FT0[256];
static uint32_t FT1[256];
static uint32_t FT2[256];
static uint32_t FT3[256];
```

This might not seem like a lot on desktop/laptop/mobile, but is a lot in the context of embedded microcontrollers, which sometimes only have 38 KB of RAM memory in total.

This could be done more efficiently by making the lookup tables `static const` and having them populated at compile-time. The disadvantage of this is that the hardcoded constants will be harder to audit (but then again, if the constants are wrong, the tests won't pass).

**Comment by tiod4420** [comment]
Hello,

Thank you for your suggestion, as you mentioned, we were not targeting MCU at first, so we didn't face the issue. But as you mentioned, it can be easily fixed with `static const` tables.

We will add the possibility to use precomputed tables with a preprocessor macro that can be enabled at compile time.

We're currently fixing another unrelated issue, which we will merge soon, so we will also include the ROM tables in the next release.

Thank you.

**Comment by redfast00** [comment]
Thanks for the quick reply! I've added a comment in the PR, I think it's possible to save even more memory :)

**Comment by tiod4420** [comment]
The feature has been added, with feature flags for both having ROM tables and limiting the number of tables used. We're about to merge it to master and make a new release version.
